---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app 
  namespace: app-node 
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: node-app 
  template:
    metadata:
      name: node-app 
      labels:
        app: node-app 
    spec:
      containers:
      - name: node-app 
        image: 251815888428.dkr.ecr.us-east-1.amazonaws.com/mendix-jenkins:latest 
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service 
metadata:
  name: node-app-svc
  namespace: app-node 
  labels:
    app: node-app
spec:
  selector:
    app: node-app
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      name: http 
