---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-node-app 
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: sample-node-app 
  template:
    metadata:
      name: sample-node-app 
      labels:
        app: sample-node-app 
    spec:
      containers:
      - name: sample-node-app 
        image: 251815888428.dkr.ecr.us-east-1.amazonaws.com/mendix-jenkins:latest 
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service 
metadata:
  name: sample-node-app-svc
  labels:
    app: sample-node-app
spec:
  selector:
    app: sample-node-app
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      name: http 
